<?php
/**
 * Custom Code Loader
 *
 * Loads custom code files generated by Creator when WP Code is not available.
 * - PHP: Included on init hook
 * - CSS: Enqueued on wp_enqueue_scripts
 * - JS: Enqueued on wp_enqueue_scripts
 *
 * @package CreatorCore
 */

namespace CreatorCore\Executor;

defined( 'ABSPATH' ) || exit;

/**
 * Class CustomCodeLoader
 *
 * Responsible for loading and enqueueing custom code files.
 */
class CustomCodeLoader {

	/**
	 * Base directory for custom files
	 *
	 * @var string
	 */
	private string $base_dir;

	/**
	 * Base URL for custom files
	 *
	 * @var string
	 */
	private string $base_url;

	/**
	 * Custom file paths
	 */
	private const FILE_PHP = 'custom-code/codice-custom.php';
	private const FILE_CSS = 'custom-code/codice-custom.css';
	private const FILE_JS  = 'custom-code/codice-custom.js';

	/**
	 * Constructor
	 */
	public function __construct() {
		$this->base_dir = CREATOR_CORE_PATH;
		$this->base_url = CREATOR_CORE_URL;
	}

	/**
	 * Initialize the loader
	 *
	 * @return void
	 */
	public function init(): void {
		// Load PHP custom code early (after plugins loaded)
		add_action( 'plugins_loaded', [ $this, 'load_custom_php' ], 20 );

		// Enqueue CSS and JS on frontend
		add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_custom_assets' ], 100 );

		// Also enqueue in admin if needed
		add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_custom_assets_admin' ], 100 );
	}

	/**
	 * Load custom PHP code
	 *
	 * @return void
	 */
	public function load_custom_php(): void {
		$php_file = $this->base_dir . self::FILE_PHP;

		if ( file_exists( $php_file ) && is_readable( $php_file ) ) {
			// Validate file has content beyond just the header
			$content = file_get_contents( $php_file );

			// Check if there's actual code (not just header comments)
			if ( $this->has_actual_code( $content ) ) {
				try {
					include_once $php_file;
				} catch ( \Throwable $e ) {
					// Log error but don't break the site
					error_log( sprintf(
						'Creator Custom PHP Error: %s in %s on line %d',
						$e->getMessage(),
						$e->getFile(),
						$e->getLine()
					) );

					// Optionally notify admin
					if ( is_admin() && current_user_can( 'manage_options' ) ) {
						add_action( 'admin_notices', function() use ( $e ) {
							echo '<div class="notice notice-error"><p>';
							echo '<strong>Creator:</strong> ';
							echo esc_html( sprintf(
								'Error in custom PHP code: %s',
								$e->getMessage()
							) );
							echo '</p></div>';
						} );
					}
				}
			}
		}
	}

	/**
	 * Enqueue custom CSS and JS on frontend
	 *
	 * @return void
	 */
	public function enqueue_custom_assets(): void {
		$this->enqueue_custom_css();
		$this->enqueue_custom_js();
	}

	/**
	 * Enqueue custom assets in admin (if they target admin)
	 *
	 * @return void
	 */
	public function enqueue_custom_assets_admin(): void {
		// For now, don't load custom assets in admin
		// This could be made configurable later
	}

	/**
	 * Enqueue custom CSS
	 *
	 * @return void
	 */
	private function enqueue_custom_css(): void {
		$css_file = $this->base_dir . self::FILE_CSS;

		if ( file_exists( $css_file ) && is_readable( $css_file ) ) {
			// Check if file has actual CSS content
			$content = file_get_contents( $css_file );

			if ( $this->has_actual_code( $content, 'css' ) ) {
				$version = filemtime( $css_file );

				wp_enqueue_style(
					'creator-custom-css',
					$this->base_url . self::FILE_CSS,
					[],
					$version
				);
			}
		}
	}

	/**
	 * Enqueue custom JavaScript
	 *
	 * @return void
	 */
	private function enqueue_custom_js(): void {
		$js_file = $this->base_dir . self::FILE_JS;

		if ( file_exists( $js_file ) && is_readable( $js_file ) ) {
			// Check if file has actual JS content
			$content = file_get_contents( $js_file );

			if ( $this->has_actual_code( $content, 'js' ) ) {
				$version = filemtime( $js_file );

				wp_enqueue_script(
					'creator-custom-js',
					$this->base_url . self::FILE_JS,
					[ 'jquery' ], // Common dependency
					$version,
					true // Load in footer
				);
			}
		}
	}

	/**
	 * Check if content has actual code (not just header/comments)
	 *
	 * @param string $content File content.
	 * @param string $type    File type (php, css, js).
	 * @return bool
	 */
	private function has_actual_code( string $content, string $type = 'php' ): bool {
		// Look for Creator modification markers
		if ( strpos( $content, 'CREATOR MODIFICATION' ) !== false ) {
			return true;
		}

		// Remove comments and whitespace, check if anything remains
		switch ( $type ) {
			case 'css':
				// Remove CSS comments
				$stripped = preg_replace( '/\/\*.*?\*\//s', '', $content );
				break;

			case 'js':
				// Remove JS comments (single and multi-line)
				$stripped = preg_replace( '/\/\/.*$/m', '', $content );
				$stripped = preg_replace( '/\/\*.*?\*\//s', '', $stripped );
				// Remove IIFE wrapper
				$stripped = preg_replace( '/^\s*\(function\(\)\s*\{\s*[\'"]use strict[\'"];\s*/s', '', $stripped );
				$stripped = preg_replace( '/\}\)\(\);\s*$/s', '', $stripped );
				break;

			case 'php':
			default:
				// Remove PHP comments
				$stripped = preg_replace( '/\/\*.*?\*\//s', '', $content );
				$stripped = preg_replace( '/\/\/.*$/m', '', $stripped );
				$stripped = preg_replace( '/#.*$/m', '', $stripped );
				// Remove PHP tags
				$stripped = preg_replace( '/<\?php|\?>/', '', $stripped );
				// Remove marker lines
				$stripped = preg_replace( '/===\s*CREATOR\s+CODE\s+BLOCKS\s+(START|END)\s*===/i', '', $stripped );
				break;
		}

		// Remove whitespace and check if content remains
		$stripped = preg_replace( '/\s+/', '', $stripped ?? '' );
		$stripped = str_replace( [ 'definedABSPATHexit', 'usestrict' ], '', $stripped ?? '' );

		return strlen( $stripped ?? '' ) > 50; // Arbitrary threshold for "real" code
	}

	/**
	 * Check if custom code files exist and have content
	 *
	 * @return array Status of each file type.
	 */
	public function get_status(): array {
		return [
			'php' => [
				'exists'      => file_exists( $this->base_dir . self::FILE_PHP ),
				'has_content' => $this->file_has_content( self::FILE_PHP, 'php' ),
			],
			'css' => [
				'exists'      => file_exists( $this->base_dir . self::FILE_CSS ),
				'has_content' => $this->file_has_content( self::FILE_CSS, 'css' ),
			],
			'js' => [
				'exists'      => file_exists( $this->base_dir . self::FILE_JS ),
				'has_content' => $this->file_has_content( self::FILE_JS, 'js' ),
			],
		];
	}

	/**
	 * Check if a file has actual content
	 *
	 * @param string $file File path relative to base_dir.
	 * @param string $type File type.
	 * @return bool
	 */
	private function file_has_content( string $file, string $type ): bool {
		$path = $this->base_dir . $file;

		if ( ! file_exists( $path ) ) {
			return false;
		}

		$content = file_get_contents( $path );
		return $this->has_actual_code( $content, $type );
	}
}
